import Head from 'next/head';
import About from '../components/about';
import Home from '../components/home';

export default function App() {
  return (
    <>
      <Head>
        <title>Beadle:Dev</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Home />
        <About />
      </main>
    </>
  );
}
