import Head from 'next/head';
import Home from '../components/home';

export default function App() {
  return (
    <>
      <Head>
        <title>Beadle:Dev</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Home />
        <section id='about' style={{ height: '50rem', width: '80%', background: 'lightYellow', margin: '5rem auto 0' }}>
          This is my about me content
        </section>
        <section id='skills' style={{ height: '50rem', width: '80%', background: 'gold', margin: '5rem auto 0' }}>
          This is my github content
        </section>
      </main>
    </>
  );
}
